### ISSUE TITLE
Experimental UI

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/GPA_Calculator#28]
@PetalCat / @ParkerH27 is currently building a new UI that doesn't use `w3.css`.
```[tasklist]
## TODO List
- [x] Wipe Styles
- [x] Begin using Tailwind via the [CDN](https://tailwindcss.com/docs/installation/play-cdn)
- [ ] Remove support help page.... Directions are enough
- [ ] Remove Easter Egg (partially done)
- [x] Add new #20
- [x] Add new backgrounds
- [ ] Add background switching Easter Egg
- [ ] Update theming to match backgrounds
- [ ] Use the Tailwind [CLI](https://tailwindcss.com/docs/installation) with [Vite](https://tailwindcss.com/docs/guides/vite)
```
